#basic pipeline that uses docker

image: maven:3.6-jdk-8

stages:
        - build
        - test
        - deploy

build-job:
        stage: build
        script:
                - mvn compile

test-job:
        stage: test
        script:
                - mvn clean test

deploy-job:
        stage: deploy
        script:
                - mvn -Drepo.login=admin -Drepo.pwd=DevEngineering123! clean deploy
